{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-gitlab-runner-serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: "{{ $.Release.Name }}-gitlab-runner-role"
  namespace: "{{ default .Release.Namespace .Values.runners.namespace }}"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-gitlab-role-binding"
  namespace: "{{ default .Release.Namespace .Values.runners.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $.Release.Name }}-gitlab-runner-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-gitlab-runner-serviceaccount"
    namespace: "{{ .Release.Namespace }}"
{{- end }}